import { ApplicationAccessibility } from './ApplicationAccessibility';
import { ApplicationBootLaunchParams } from './ApplicationBootLaunchParams';
import { ApplicationClass } from './ApplicationClass';
import { ApplicationKeyFilterTable } from './ApplicationKeyFilterTable';
import { ApplicationMediaExtension } from './ApplicationMediaExtension';
import { ApplicationMimeType } from './ApplicationMimeType';
import { ApplicationVendorExtension } from './ApplicationVendorExtension';
import { ApplicationWindowGroup } from './ApplicationWindowGroup';
import { PreviewMetadata } from './PreviewMetadata';

export interface Application {
    networkStableTimeout: number;
    checkUpdateOnLaunch: boolean;
    requiredPermissions: string[];
    class: ApplicationClass;
    title: string;
    allowWidget: boolean;
    icon: string;
    tileSize: string;
    inAppSetting: boolean;
    closeOnRotation: boolean;
    nativeLifeCycleInterfaceVersion: number;
    folderPath: string;
    transparent: boolean;
    version: string;
    trustLevel: string;
    hasPromotion: boolean;
    enableCBSPolicy: boolean;
    lockable: boolean;
    systemApp: boolean;
    mediumLargeIcon: string;
    main: string;
    visible: boolean;
    privilegedJail: boolean;
    inspectable: boolean;
    defaultWindowType: string;
    vendor: string;
    accessibility: ApplicationAccessibility;
    deeplinkingParams: string;
    type: string;
    supportTouchMode: string;
    spinnerOnLaunch: boolean;
    installTime: number;
    id: string;
    disableBackHistoryAPI: boolean;
    enableBackgroundRun: boolean;
    handlesRelaunch: boolean;
    noSplashOnLaunch: boolean;
    useCORSWhitelist: string;
    removable: boolean;
    CPApp: boolean;
    uiRevision: any;
    unmovable: boolean;
    extraLargeIcon: string;
    previewMetadata: PreviewMetadata;
    requiredEULA: string;
    bgImage: string;
    largeIcon: string;
    internalInstallationOnly: boolean;
    iconColor: string;
    resolution: string;
    standAloneLaunchable: boolean;
    storageUseMode: string;
    appsize: number;
    binId: number;
    splashBackground: string;
    bgColor: string;
    dialAppName: string;
    v8SnapshotFile: string;
    useNativeScroll: boolean;
    enablePigScreenSaver: boolean;
    usePrerendering: boolean;
    sysAssetsBasePath: string;
    supportPortraitMode: boolean;
    voiceControl: string;
    supportQuickStart: boolean;
    windowGroup: ApplicationWindowGroup;
    mediaExtension: ApplicationMediaExtension;
    resolutionIndependent: boolean;
    handleExitKey: boolean;
    appDescription: string;
    supportTouchInputDevice: boolean;
    miniicon: string;
    supportRollingScreenMode: boolean;
    supportsVoiceBrowsing: boolean;
    mimeTypes: ApplicationMimeType[];
    requiredMemory: number;
    handleScreenRemoteKey: boolean;
    bootLaunchParams: ApplicationBootLaunchParams;
    useGraphicCamera: boolean;
    useCamera: boolean;
    allowAudioCapture: boolean;
    allowVideoCapture: boolean;
    imageForRecents: string;
    suspendDOMTime: number;
    vendorExtension: ApplicationVendorExtension;
    mediumIcon: string;
    keyFilterTable: ApplicationKeyFilterTable[];
};
