//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7

use crate::user;
use chrono::Local;
use sea_orm::entity::prelude::*;
use sea_orm::ActiveValue;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    #[serde(skip_deserializing)]
    pub id: Uuid,
    pub email: String,
    #[serde(skip_serializing)]
    pub password: String,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    #[serde(skip_deserializing)]
    pub create_date: DateTime,
    #[serde(skip_deserializing)]
    pub update_date: DateTime,
}

impl Model {
    pub fn to_json(&self) -> Result<String, serde_json::error::Error> {
        serde_json::to_string(self)
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {
    fn before_save(mut self, _: bool) -> Result<Self, DbErr> {
        self.id = ActiveValue::Set(Uuid::new_v4());
        self.update_date = ActiveValue::Set(Local::now().naive_local());
        Ok(self)
    }
}
